version: '3'
services:
  python366:
    container_name: PWS_py366
    image: eronde/pws
    # build: 
    #   context: ./python366
    environment:
      ENV: SHELL
    # tty: true
    volumes:
      - ${PWD}/tests:/code/tests
      - ${PWD}/py_word_suggest:/code/py_word_suggest
      - ${PWD}/pytest.ini:/code/pytest.ini
      - ${PWD}/Makefile:/code/Makefile
      - ${PWD}/run_tests.sh:/code/run_tests.sh
